name = "search-image-mcp-cloudflare"
main = "src/index.ts"
compatibility_date = "2024-12-01"
node_compat = true

[vars]
# 環境変数としてUnsplashのアクセスキーを設定
# UNSPLASH_ACCESS_KEY = "your-unsplash-access-key"

# 本番環境用のシークレット（wrangler secret putで設定）
# [secrets]
# UNSPLASH_ACCESS_KEY